void firstPass(char line[]);
void secondPass(char line[]);
void counterSetup();
void countZero();
int dataParse(unsigned char type);
int encodeCommand(int index);
int nonOperand();
int oneOperand();
int twoOperands();
int encodeOperands(int type);
int getLabelAdd(char *str);
void addExtern(char *label, int add);
int isError();
void updateAddOfSymbols();
int updateAddOfEntry(char *str);
void makeFiles(char *name);
void clearGlobalStructs();
void clearExternTable();
void clearEntryTable();
void clearObjectTable();
